name: main

on:
  push:
    branches: [ galactic ]
  pull_request:
    branches: [ galactic ]

jobs:
  gazebo-ros-pkgs:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout gazebo_ros_pkgs
        uses: actions/checkout@v2
        with:
          path: gazebo_ros_pkgs

      # Run docker build
      - name: Run docker build
        run: |
          set -eux
          mkdir bin
          pushd gazebo_ros_pkgs
          ./build.sh ../bin/
          ls ../bin

      - uses: jfrog/setup-jfrog-cli@v2
        env:
          JF_ARTIFACTORY_1: ${{ secrets.ARTIFACTORY_TOKEN }}

      - name: Upload to Artifactory
        env:
          ARTIFACTORY_GEN_REPO: gen-public-local
          BUILD_NAME: gazebo-ros-pkgs
          CI: true
        if: github.event_name == 'push'
        run: |
          set -exu
          jfrog rt ping
          pkg=$(find bin -name 'gazebo_ros_pkgs*.tar.gz')
          pkg_name=$(basename $pkg)
          jfrog rt u --target-props COMMIT="$GITHUB_SHA" \
                     --build-name "$BUILD_NAME" \
                     --build-number "$GITHUB_SHA" \
                     "$pkg" \
                     "$ARTIFACTORY_GEN_REPO/builds/gazebo-ros-pkgs/$pkg_name"
          jfrog rt build-publish "$BUILD_NAME" "$GITHUB_SHA"
          jfrog rt bpr "$BUILD_NAME" "$GITHUB_SHA" "$ARTIFACTORY_GEN_REPO" \
                       --status dev \
                       --comment "development build"
          jfrog rt cp --flat \
                      "$ARTIFACTORY_GEN_REPO/builds/gazebo-ros-pkgs/$pkg_name" \
                      "$ARTIFACTORY_GEN_REPO/builds/gazebo-ros-pkgs/latest/gazebo_ros_pkgs.tar.gz"

