name: gazebo-ros-pkgs-artifacts

on:
  push:
    branches: [ galactic ]
  pull_request:
    branches: [ galactic ]

jobs:
  gazebo-ros-pkgs-artifacts:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gazebo-ros-pkgs
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/tiiuae/gazebo-ros-pkgs-artifacts
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build gazebo-ros-pkgs-artifacts image and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
